name: Build and Upload

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Run installResources.ps1
      shell: pwsh
      run: ./installResources.ps1

    - name: Build project to .exe
      run: |
        pyinstaller.exe --onefile main.py

    - name: Upload .exe artifact
      uses: actions/upload-artifact@v3
      with:
        name: built
        path: dist/main.exe
